version: '3'
services:
  app:
    build: .
    ports:
      - '8200:8080'
    volumes:
      - ./groovy_thing_back:/work/groovy_thing_back
      - ./credentials.json:/work/credentials.json
    env_file:
      - .env
    command: >
      uvicorn groovy_thing_back.main:app
      --host 0.0.0.0
      --port 8080
      --reload
